
name: Generate SBOM with Trivy

on:
  push:
    branches:
      - main  # adjust this to match your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.tar.gz
        tar zxvf trivy_0.20.0_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/
    
    - name: Scan Docker image with Trivy
      run: |
        trivy image --format sbom --output report.sbom your-docker-image:latest
    
    - name: Print SBOM report
      run: |
        cat report.sbom
